[package]
name = "indiafoss24"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
chrono = "0.4.38"
icalendar = "0.16.5"
reqwest = { version = "0.12.7", features = ["json"] }
serde_json = "1.0.127"
tokio = { version = "1.40.0", features = ["full"] }
